INSERT INTO tbl3Log_Staff_MCoursesAlloc ( FK_curr_StaffMCourseAlloc, FK_StaffID, FK_MCourseID, Allocated )
SELECT tbl3curr_Staff_MCourseAlloc.ID_StaffMCourse_curr, tbl3curr_Staff_MCourseAlloc.FK_StaffID, tbl3curr_Staff_MCourseAlloc.FK_MCourseID, tbl3curr_Staff_MCourseAlloc.Allocate
FROM tbl3curr_Staff_MCourseAlloc LEFT JOIN tbl3Log_Staff_MCoursesAlloc ON tbl3curr_Staff_MCourseAlloc.ID_StaffMCourse_curr = tbl3Log_Staff_MCoursesAlloc.FK_curr_StaffMCourseAlloc
GROUP BY tbl3curr_Staff_MCourseAlloc.ID_StaffMCourse_curr, tbl3curr_Staff_MCourseAlloc.FK_StaffID, tbl3curr_Staff_MCourseAlloc.FK_MCourseID, tbl3curr_Staff_MCourseAlloc.Allocate, tbl3Log_Staff_MCoursesAlloc.FK_curr_StaffMCourseAlloc, tbl3Log_Staff_MCoursesAlloc.FK_StaffID, tbl3Log_Staff_MCoursesAlloc.FK_MCourseID
HAVING (((tbl3Log_Staff_MCoursesAlloc.FK_curr_StaffMCourseAlloc) Is Null));

